# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faixas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.FloatField(default=0, verbose_name=b'Pre\xc3\xa7o')),
                ('ficheiro', models.FileField(default=0, upload_to=b'Music')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='faixas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loja.Faixas'),
        ),
    ]
