# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0002_auto_20170612_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='faixas',
        ),
        migrations.AddField(
            model_name='faixas',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Loja.Album'),
        ),
    ]
