# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0003_auto_20170612_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faixas',
            new_name='Faixa',
        ),
    ]
