# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0004_auto_20170612_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='faixa_1',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_10',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_11',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_12',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_13',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_14',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_15',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_2',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_3',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_4',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_5',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_6',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_7',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_8',
        ),
        migrations.RemoveField(
            model_name='album',
            name='faixa_9',
        ),
        migrations.AddField(
            model_name='faixa',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
