# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0005_auto_20170612_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixa',
            name='ficheiro',
            field=models.FileField(blank=True, upload_to=b'Music'),
        ),
    ]
