# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('artigo', models.TextField()),
                ('sumario', models.CharField(blank=True, max_length=350)),
                ('imagem', models.ImageField(blank=True, upload_to='Artigos')),
                ('tema', models.CharField(choices=[('Not\xedcias', 'Not\xedcias'), ('Tecnologia', 'Tecnologia'), ('Audio', 'Audio'), ('Video', 'Video'), ('Ci\xeancia', 'Ci\xeancia'), ('Programa\xe7\xe3o', 'Programa\xe7\xe3o'), ('Geral', 'Geral'), ('Cultura', 'Cultura'), ('Web', 'Web')], default='Geral', max_length=20)),
                ('data', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('r', 'Revision')], default='d', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('departamentos', models.CharField(blank=True, max_length=100)),
                ('tutor', models.BooleanField(default=False)),
                ('autor', models.BooleanField(default=False)),
                ('editorial', models.CharField(blank=True, max_length=140)),
                ('Bio', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='profiles')),
                ('estado', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn'), ('r', 'Revision')], default='r', max_length=1)),
            ],
        ),
    ]
