# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigos',
            new_name='Artigo',
        ),
    ]
