# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0002_auto_20170523_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='estado',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='estado',
            new_name='status',
        ),
    ]
