# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0005_auto_20170523_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='informacao',
            field=models.TextField(default='Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna...'),
        ),
    ]
