# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0007_auto_20170523_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='artigos'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='perfis'),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='capa',
            field=models.ImageField(blank=True, upload_to='projectos'),
        ),
    ]
