# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0008_auto_20170524_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='imagem',
            new_name='perfil',
        ),
    ]
