# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0009_auto_20170524_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='who',
            field=models.ManyToManyField(to='Ek.Pessoa'),
        ),
    ]
