# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0011_remove_artigo_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='artigos',
            field=models.ManyToManyField(to='Ek.Artigo'),
        ),
    ]
