# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0012_pessoa_artigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='artigos',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autor',
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ManyToManyField(to='Ek.Pessoa'),
        ),
    ]
