# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0014_remove_artigo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ek.Pessoa'),
        ),
    ]
