# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0015_artigo_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'verbose_name_plural': 'Artigos, Blogues e Not\xedcias'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Usu\xe1rios do Site'},
        ),
        migrations.AlterModelOptions(
            name='projecto',
            options={'verbose_name_plural': 'Projectos da Empresa'},
        ),
        migrations.AddField(
            model_name='artigo',
            name='richmedia',
            field=models.BooleanField(default=False),
        ),
    ]
