# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0016_auto_20170525_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('preco', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('desconto', models.FloatField(default=0)),
                ('download', models.BooleanField(default=False)),
                ('devolucao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Productos \xe0 venda',
            },
        ),
    ]
