# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0018_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='origem',
        ),
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('a', 'Audio'), ('i', 'Imagem'), ('v', 'Video'), ('p', 'PDF'), ('m', 'Muse Template'), ('s', 'Sketch Template'), ('l', 'Ilustra\xe7\xe3o')], default='a', max_length=1),
        ),
    ]
