# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0020_auto_20170526_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ficheiros_a_vender',
            field=models.FileField(blank=True, upload_to='Vendas'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('a', 'Audio'), ('i', 'Imagem'), ('v', 'Video'), ('p', 'PDF'), ('m', 'Muse Template'), ('s', 'Sketch Template'), ('l', 'Ilustra\xe7\xe3o')], default='a', max_length=15),
        ),
    ]
