# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0021_auto_20170526_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
