# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0022_item_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
