# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0023_artigo_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='marca',
        ),
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
