# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 03:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0024_auto_20170530_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoCliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('website', models.URLField()),
                ('tipoDoProjecto', models.CharField(choices=[('a', 'Produ\xe7\xe3o de \xc1udio'), ('i', 'Ilustra\xe7\xe3o'), ('v', 'Produ\xe7\xe3o e/ou Edi\xe7\xe3o de V\xeddeo'), ('f', 'Fotografia'), ('w', 'Cria\xe7\xe3o de Website'), ('d', 'Registrar Dom\xednio'), ('l', 'Logotipo')], default='w', max_length=1)),
                ('descricaoDoProjecto', models.TextField()),
                ('expectativaDeEntrega', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
