# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0025_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('faixas', models.IntegerField()),
                ('download', models.FileField(upload_to='Vendas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('a', '\xc1lbum'), ('i', 'Imagem'), ('v', 'V\xeddeo'), ('p', 'Livro'), ('m', 'Muse Template'), ('s', 'Sketch Template'), ('l', 'Ilustra\xe7\xe3o')], default='a', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Loja'},
        ),
        migrations.AlterModelOptions(
            name='projecto',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AddField(
            model_name='projecto',
            name='cor_1',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='projecto',
            name='cor_2',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='projecto',
            name='cor_3',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='projecto',
            name='cor_4',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('a', '\xc1lbum'), ('i', 'Imagem'), ('v', 'V\xeddeo'), ('p', 'Livro'), ('m', 'Muse Template'), ('s', 'Sketch Template'), ('l', 'Ilustra\xe7\xe3o')], default='a', max_length=15),
        ),
    ]
