# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0027_auto_20170601_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumitem',
            name='faixa_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_11',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_12',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='faixa_9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ek.AlbumItem'),
        ),
    ]
