# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0030_auto_20170601_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=50)),
                ('gravadora', models.CharField(max_length=50)),
                ('faixas', models.IntegerField()),
                ('faixa_1', models.CharField(blank=True, max_length=50)),
                ('faixa_2', models.CharField(blank=True, max_length=50)),
                ('faixa_3', models.CharField(blank=True, max_length=50)),
                ('faixa_4', models.CharField(blank=True, max_length=50)),
                ('faixa_5', models.CharField(blank=True, max_length=50)),
                ('faixa_6', models.CharField(blank=True, max_length=50)),
                ('faixa_7', models.CharField(blank=True, max_length=50)),
                ('faixa_8', models.CharField(blank=True, max_length=50)),
                ('faixa_9', models.CharField(blank=True, max_length=50)),
                ('faixa_10', models.CharField(blank=True, max_length=50)),
                ('faixa_11', models.CharField(blank=True, max_length=50)),
                ('faixa_12', models.CharField(blank=True, max_length=50)),
                ('faixa_13', models.CharField(blank=True, max_length=50)),
                ('faixa_14', models.CharField(blank=True, max_length=50)),
                ('faixa_15', models.CharField(blank=True, max_length=50)),
                ('ficheiro', models.FileField(upload_to='Vendas')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('lancamento', models.DateField(default=datetime.date.today, verbose_name='Lan\xe7amento')),
                ('editora', models.CharField(max_length=50)),
                ('paginas', models.IntegerField(verbose_name='P\xe1ginas')),
                ('sinopse', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='albumitem',
            name='cantor',
        ),
        migrations.DeleteModel(
            name='TipoDeItem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='teste',
        ),
        migrations.DeleteModel(
            name='AlbumItem',
        ),
        migrations.AddField(
            model_name='item',
            name='album',
            field=models.ManyToManyField(blank=True, to='Ek.Album'),
        ),
        migrations.AddField(
            model_name='item',
            name='livro',
            field=models.ManyToManyField(blank=True, to='Ek.Livro'),
        ),
    ]
