# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0032_auto_20170601_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='album',
        ),
        migrations.RemoveField(
            model_name='item',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='livro',
        ),
        migrations.AddField(
            model_name='album',
            name='capa',
            field=models.ImageField(default=0, upload_to='Loja/Albums'),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(default=0, upload_to='Loja/Livros'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
