# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0033_auto_20170601_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='download',
            field=models.BooleanField(default=True, verbose_name='Pra baixar'),
        ),
        migrations.AddField(
            model_name='album',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Pre\xe7o em d\xf3lares'),
        ),
        migrations.AddField(
            model_name='livro',
            name='download',
            field=models.BooleanField(default=True, verbose_name='Pra baixar'),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Pre\xe7o em d\xf3lares'),
        ),
        migrations.AlterField(
            model_name='album',
            name='ficheiro',
            field=models.FileField(default=0, upload_to='Vendas', verbose_name='Ficheiro a baixar'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ficheiro',
            field=models.FileField(default=0, upload_to='Vendas', verbose_name='Ficheiro a baixar'),
        ),
    ]
