# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0034_auto_20170601_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='cap_1',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_10',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_11',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_12',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_13',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_14',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_15',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_2',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_3',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_4',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_5',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_6',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_7',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_8',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='livro',
            name='cap_9',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
