# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0035_auto_20170601_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('d', 'Rascunho'), ('p', 'Publicado'), ('o', 'Oculto'), ('r', 'Em Revis\xe3o')], default='d', max_length=1),
        ),
    ]
