# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0036_album_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Projecto',
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.DeleteModel(
            name='Artigo',
        ),
    ]
