# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ek', '0037_auto_20170612_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='perfil',
            new_name='imagem',
        ),
    ]
