# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 07:20

from __future__ import unicode_literals
import uuid
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ek', '0037_auto_20170612_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('richmedia', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('artigo', models.TextField()),
                ('sumario', models.CharField(blank=True, max_length=350)),
                ('imagem', models.ImageField(blank=True, upload_to=b'artigos')),
                ('tema', models.CharField(choices=[('N', 'Not\xedcias'), ('T', 'Tecnologia'), ('A', 'Audio'), ('V', 'Video'), ('S', 'Ci\xeancia'), ('P', 'Programa\xe7\xe3o'), ('G', 'Geral'), ('C', 'Cultura'), ('W', 'Web')], default=b'G', max_length=20)),
                ('data', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('d', 'Rascunho'), ('p', 'Publicado'), ('o', 'Oculto'), ('r', 'Em Revis\xe3o')], default=b'd', max_length=1)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ek.Pessoa')),
            ],
            options={
                'verbose_name_plural': 'Artigos, Blogues e Not\xedcias',
            },
        ),
    ]
