# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:14
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='texto',
            field=markdownx.models.MarkdownxField(default=b'lorem ipsum'),
        ),
    ]
