# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_artigo_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='texto',
        ),
        migrations.AddField(
            model_name='texto',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Artigo'),
        ),
    ]
