# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20170706_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto',
            name='texto',
        ),
    ]
