# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('informacao', models.TextField(default='Etiam porta sem malesuada magna mollis euismod. Praesent commodo cursus magna...')),
                ('detalhes_tecnicos', models.CharField(blank=True, max_length=200)),
                ('cor_1', models.CharField(blank=True, max_length=7)),
                ('cor_2', models.CharField(blank=True, max_length=7)),
                ('cor_3', models.CharField(blank=True, max_length=7)),
                ('cor_4', models.CharField(blank=True, max_length=7)),
                ('capa', models.ImageField(blank=True, upload_to='projectos')),
                ('local', models.CharField(max_length=100)),
                ('dias', models.IntegerField(default=1)),
                ('destaque', models.BooleanField(default=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('d', 'Rascunho'), ('p', 'Publicado'), ('o', 'Oculto'), ('r', 'Em Revis\xe3o')], default='r', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
