# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='cor_em_HEX',
            field=models.CharField(max_length=7),
        ),
    ]
